name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, electron]

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies globally (root)
      - name: Install dependencies
        run: npm ci

      # Build server
      - name: Build server and client
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run build-all

      # Start server
      - name: Start server and client in background
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          nohup npm run dev > dev.log 2>&1 & 
          npx wait-on http://localhost:5000 --timeout 30000

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}
